# -*- coding: utf-8 -*-
# Dati delle 26 schede dell'Alfabetiere A-Z.
# Le illustrazioni da colorare sono pittogrammi ARASAAC nella variante in
# bianco e nero (autore Sergio Palao, origine ARASAAC, CC BY-NC-SA 4.0),
# scaricati in static/pittogrammi/arasaac-bn/ e citati per id nel registro.

LETTERE = [
  dict(l="A", parola="Allerta", img="alf-a-allerta",
    alt='Cartello triangolare di pericolo con un punto esclamativo.',
    dida='Il cartello dell’allerta avvisa che può arrivare un pericolo.',
  ),
  dict(l="B", parola="Barella", img="alf-b-barella",
    alt='Barella con le ruote, vista di lato.',
    dida='Sulla barella si trasporta chi si è fatto male.',
  ),
  dict(l="C", parola="Casco", img="alf-c-casco",
    alt='Elmetto di protezione da lavoro.',
    dida='Il casco protegge la testa dei soccorritori.',
  ),
  dict(l="D", parola="Drone", img="alf-d-drone",
    alt='Drone con quattro eliche e una piccola telecamera.',
    dida='Il drone vola e aiuta a cercare le persone.',
  ),
  dict(l="E", parola="Elicottero", img="alf-e-elicottero",
    alt='Elicottero in volo, visto di lato.',
    dida='L’elicottero porta i soccorsi dove le strade non arrivano.',
  ),
  dict(l="F", parola="Fiume", img="alf-f-fiume",
    alt='Fiume che scorre fra due rive alberate.',
    dida='Quando piove tanto il fiume può ingrossarsi.',
  ),
  dict(l="G", parola="Guanti", img="alf-g-guanti",
    alt='Un paio di guanti da lavoro.',
    dida='I guanti proteggono le mani di chi lavora.',
  ),
  dict(l="H", parola="Helipad", img="alf-h-piazzola", muta=True,
    alt='Elicottero che atterra su una piazzola con la lettera H.',
    dida='In italiano la H da sola non ha suono. A terra, però, la H grande indica la piazzola.',
    spiega='Helipad è una parola inglese. È la piazzola dove atterra l’elicottero: si riconosce dalla grande H disegnata a terra.',
  ),
  dict(l="I", parola="Incendio", img="alf-i-incendio",
    alt='Le fiamme di un incendio.',
    dida='Se vedi un incendio lo dici subito a un adulto.',
  ),
  dict(l="J", parola="Joystick", img="alf-j-joystick", ospite=True,
    alt='Radiocomando con la leva del joystick.',
    dida='Con il joystick si guida il drone che cerca le persone.',
    spiega='Joystick è una parola inglese. È la leva che si muove con la mano per guidare il drone.',
  ),
  dict(l="K", parola="Kit", img="alf-k-kit", ospite=True,
    alt='Valigetta di pronto soccorso con la croce.',
    dida='Nel kit c’è tutto quello che serve se bisogna uscire di casa.',
  ),
  dict(l="L", parola="Luogo sicuro", img="alf-l-luogo-sicuro",
    alt='Cortile aperto di una scuola, con gli alberi.',
    dida='Il luogo sicuro è dove ci si ritrova quando si esce.',
  ),
  dict(l="M", parola="Mappa", img="alf-m-mappa",
    alt='Mappa di carta aperta, con le strade.',
    dida='La mappa mostra le strade e i luoghi sicuri.',
  ),
  dict(l="N", parola="Numero 112", img="alf-n-telefono",
    alt='Telefono con la cornetta e i tasti.',
    dida='Il 112 è il numero unico per chiedere aiuto.',
  ),
  dict(l="O", parola="Ordine", img="alf-o-ordine",
    alt="Cinque persone in fila, una dietro l'altra.",
    dida='In fila, con ordine e senza spingere, si esce meglio.',
  ),
  dict(l="P", parola="Protezione Civile", img="alf-p-protezione-civile",
    alt='Due volontari in divisa accanto a un mezzo di soccorso.',
    dida='La Protezione Civile aiuta le persone quando c’è un pericolo.',
  ),
  dict(l="Q", parola="Quaderno", img="alf-q-quaderno",
    alt="Quaderno ad anelli con l'etichetta sulla copertina.",
    dida='Sul quaderno scriviamo quello che impariamo.',
  ),
  dict(l="R", parola="Radio", img="alf-r-radio",
    alt="Radio ricetrasmittente portatile con l'antenna.",
    dida='Con la radio i volontari si parlano anche senza telefono.',
  ),
  dict(l="S", parola="Sicurezza", img="alf-s-sicurezza",
    alt="Bambino seduto nel seggiolino dell'auto, con le cinture allacciate.",
    dida='Stare al sicuro vuol dire seguire le regole con calma.',
  ),
  dict(l="T", parola="Terremoto", img="alf-t-terremoto",
    alt='Persona che si ripara sotto un tavolo.',
    dida='Se la terra trema, ti ripari sotto il tavolo, proteggi la testa e aspetti che la scossa finisca.',
  ),
  dict(l="U", parola="Uscita", img="alf-u-uscita",
    alt='Persona che esce da una porta aperta.',
    dida='La porta con la scritta uscita porta fuori, al sicuro.',
  ),
  dict(l="V", parola="Volontario", img="alf-v-volontari",
    alt="Tre volontari in divisa, uno accanto all'altro.",
    dida='Il volontario aiuta gli altri senza essere pagato.',
  ),
  dict(l="W", parola="Warning", img="alf-w-warning", ospite=True,
    alt='Cartello triangolare di pericolo con due bambini che attraversano.',
    dida='Warning e attenzione vogliono dire la stessa cosa.',
    spiega='Warning è una parola inglese. Vuol dire attenzione: la trovi sui cartelli di pericolo di tutto il mondo.',
  ),
  dict(l="X", parola="Exit", img="alf-x-exit", ospite=True,
    alt="Persona che accompagna una carrozzina verso l'uscita di emergenza.",
    dida='Exit e uscita vogliono dire la stessa cosa.',
    spiega='Exit è una parola inglese. Vuol dire uscita: si legge sui cartelli verdi negli aeroporti e nei musei.',
  ),
  dict(l="Y", parola="Yellow", img="alf-y-semaforo", ospite=True,
    alt='Semaforo con le tre luci.',
    dida='Colora di giallo: è il colore dell’allerta gialla.',
    spiega='Yellow è una parola inglese. Vuol dire giallo: è il colore dell’allerta gialla, quella che invita a stare attenti.',
  ),
  dict(l="Z", parola="Zaino", img="alf-z-zaino",
    alt='Zaino con le bretelle e la tasca davanti.',
    dida='Nello zaino metti acqua, torcia e una coperta.',
  ),
]
