#!/usr/bin/env python3
"""
Toglie da commenti, revisioni e descrizioni di PR e issue la riga di firma che
la piattaforma delle sessioni aggiunge da sola a ogni testo pubblicato su GitHub
(«Generated by [Claude Code](…)», il link alla sessione, eventuali trailer).

Perché esiste (06/10/2026). CLAUDE.md vieta qualunque riferimento allo
strumento nei testi pubblicati. La riga però la aggiunge il canale delle
sessioni a ogni scrittura, comprese le modifiche: dalla sessione non si
toglie. Un workflow GitHub Actions scrive invece con il GITHUB_TOKEN, che non
passa da quel canale, e la riga resta tolta.

Tocca solo testi scritti dall'account proprietario del repository, e solo la
coda del testo: righe di firma finali e il separatore «---» che le precede.
Il resto del testo resta identico.

Uso:
  rimuovi-firma-strumento.py --evento              # dal workflow, sul testo dell'evento
  rimuovi-firma-strumento.py --tutti [--dal AAAA-MM-GG | --giorni N] [--max N]
                             [--giri N --pausa SECONDI] [--prova]

GitHub limita le scritture (circa 500 l'ora): un giro corregge al massimo
--max testi, e con --giri lo script aspetta --pausa secondi e ricomincia
finché non resta nulla.

Variabili: GITHUB_TOKEN, GITHUB_REPOSITORY (owner/repo), GITHUB_API_URL,
GITHUB_EVENT_NAME e GITHUB_EVENT_PATH (solo --evento). Solo libreria standard.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request

API = os.environ.get("GITHUB_API_URL", "https://api.github.com").rstrip("/")
REPO = os.environ.get("GITHUB_REPOSITORY", "SviluppoItaliaDigitale/sito-pc-genzano")
OWNER = REPO.split("/")[0]
TOKEN = os.environ.get("GITHUB_TOKEN", "")

# Righe che possono chiudere un testo e vanno tolte (solo in coda).
RIGHE_FIRMA = [
    re.compile(r"^_?Generated (?:by|with) \[Claude Code\]\([^)]*\)_?\.?$", re.I),
    re.compile(r"^🤖\s*Generated (?:by|with) \[Claude Code\]\([^)]*\)\.?$", re.I),
    re.compile(r"^<?https://claude\.ai/code/session_[A-Za-z0-9_-]+>?$"),
    re.compile(r"^Claude-Session:\s*\S+$", re.I),
    re.compile(r"^Co-Authored-By:\s*Claude\b.*$", re.I),
]
RIGA_SEPARATORE = re.compile(r"^(?:-{3,}|\*{3,}|_{3,})$")


def pulisci(testo: str) -> str:
    """Restituisce il testo senza le righe di firma in coda (idempotente)."""
    if not testo:
        return testo
    righe = testo.replace("\r\n", "\n").split("\n")
    tolto = False
    while righe:
        ultima = righe[-1].strip()
        if not ultima:
            righe.pop()
            continue
        if any(p.match(ultima) for p in RIGHE_FIRMA):
            righe.pop()
            tolto = True
            continue
        if tolto and RIGA_SEPARATORE.match(ultima):
            righe.pop()
            continue
        break
    if not tolto:
        return testo
    return "\n".join(righe).rstrip()


def chiama(metodo: str, url: str, dati: dict | None = None):
    corpo = json.dumps(dati).encode() if dati is not None else None
    req = urllib.request.Request(url, data=corpo, method=metodo)
    req.add_header("Accept", "application/vnd.github+json")
    req.add_header("X-GitHub-Api-Version", "2022-11-28")
    req.add_header("User-Agent", "pcgenzano-rimuovi-firma")
    if TOKEN:
        req.add_header("Authorization", f"Bearer {TOKEN}")
    if corpo is not None:
        req.add_header("Content-Type", "application/json")
    for tentativo in range(4):
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                testo = r.read().decode() or "null"
                return json.loads(testo)
        except urllib.error.HTTPError as e:
            # Limiti secondari di GitHub sulle scritture: si aspetta e si riprova.
            if e.code in (403, 429) and tentativo < 3:
                attesa = int(e.headers.get("Retry-After") or 60)
                print(f"  limite di GitHub ({e.code}), attendo {attesa} s", flush=True)
                time.sleep(attesa)
                continue
            raise


def elenco(url: str, massimo_pagine: int = 50) -> list[dict]:
    out: list[dict] = []
    sep = "&" if "?" in url else "?"
    for pagina in range(1, massimo_pagine + 1):
        dati = chiama("GET", f"{url}{sep}per_page=100&page={pagina}") or []
        out.extend(dati)
        if len(dati) < 100:
            break
    return out


def dell_account(oggetto: dict) -> bool:
    return (oggetto.get("user") or {}).get("login") == OWNER


class Contatore:
    def __init__(self, prova: bool, massimo: int):
        self.prova, self.massimo, self.fatti, self.trovati = prova, massimo, 0, 0

    def esaurito(self) -> bool:
        return self.fatti >= self.massimo

    def correggi(self, metodo: str, url: str, campo_body: str, testo: str, etichetta: str) -> None:
        nuovo = pulisci(testo)
        if nuovo == testo:
            return
        self.trovati += 1
        if not nuovo.strip():
            print(f"  [salto] {etichetta}: senza la firma resterebbe vuoto")
            return
        if self.esaurito():
            return
        print(f"  {'[prova] ' if self.prova else ''}{etichetta}", flush=True)
        if not self.prova:
            chiama(metodo, url, {campo_body: nuovo})
            time.sleep(1.0)   # restare sotto i limiti di GitHub sulle scritture
        self.fatti += 1


def modo_evento() -> int:
    nome = os.environ.get("GITHUB_EVENT_NAME", "")
    with open(os.environ["GITHUB_EVENT_PATH"], encoding="utf-8") as f:
        ev = json.load(f)
    c = Contatore(prova=False, massimo=10)
    base = f"{API}/repos/{REPO}"
    if nome == "issue_comment":
        o = ev["comment"]
        if dell_account(o):
            c.correggi("PATCH", f"{base}/issues/comments/{o['id']}", "body", o.get("body") or "", f"commento {o['id']}")
    elif nome == "pull_request_review_comment":
        o = ev["comment"]
        if dell_account(o):
            c.correggi("PATCH", f"{base}/pulls/comments/{o['id']}", "body", o.get("body") or "", f"commento di revisione {o['id']}")
    elif nome == "pull_request_review":
        o, n = ev["review"], ev["pull_request"]["number"]
        if dell_account(o):
            c.correggi("PUT", f"{base}/pulls/{n}/reviews/{o['id']}", "body", o.get("body") or "", f"revisione {o['id']} su #{n}")
    elif nome in ("pull_request", "pull_request_target"):
        o = ev["pull_request"]
        if dell_account(o):
            c.correggi("PATCH", f"{base}/pulls/{o['number']}", "body", o.get("body") or "", f"descrizione PR #{o['number']}")
    elif nome == "issues":
        o = ev["issue"]
        if dell_account(o):
            c.correggi("PATCH", f"{base}/issues/{o['number']}", "body", o.get("body") or "", f"descrizione issue #{o['number']}")
    else:
        print(f"evento {nome!r} non gestito")
    print(f"testi corretti: {c.fatti}")
    return 0


def modo_tutti(dal: str, massimo: int, prova: bool) -> int:
    base = f"{API}/repos/{REPO}"
    since = f"{dal}T00:00:00Z"
    c = Contatore(prova=prova, massimo=massimo)

    print("Commenti su issue e PR")
    for o in elenco(f"{base}/issues/comments?since={since}"):
        if dell_account(o):
            c.correggi("PATCH", f"{base}/issues/comments/{o['id']}", "body", o.get("body") or "", f"commento {o['id']}")

    print("Commenti nelle revisioni")
    for o in elenco(f"{base}/pulls/comments?since={since}"):
        if dell_account(o):
            c.correggi("PATCH", f"{base}/pulls/comments/{o['id']}", "body", o.get("body") or "", f"commento di revisione {o['id']}")

    print("Descrizioni di PR e issue, e revisioni")
    interrotto = False
    for o in elenco(f"{base}/issues?state=all&since={since}"):
        n = o["number"]
        if "pull_request" in o:
            if dell_account(o):
                c.correggi("PATCH", f"{base}/pulls/{n}", "body", o.get("body") or "", f"descrizione PR #{n}")
            if c.esaurito() and not prova:
                # Giro pieno: inutile leggere le revisioni delle PR restanti.
                # Il resto non è contato, quindi si segnala che il lavoro non
                # è finito e il giro successivo riprende.
                interrotto = True
                break
            for r in elenco(f"{base}/pulls/{n}/reviews", massimo_pagine=3):
                if dell_account(r):
                    c.correggi("PUT", f"{base}/pulls/{n}/reviews/{r['id']}", "body", r.get("body") or "", f"revisione {r['id']} su #{n}")
        elif dell_account(o):
            c.correggi("PATCH", f"{base}/issues/{n}", "body", o.get("body") or "", f"descrizione issue #{n}")

    resto = c.trovati - c.fatti
    if interrotto:
        # Il giro si è fermato prima di vedere tutto: quanto resta non si sa,
        # ma non è zero finché un giro non arriva in fondo.
        resto = max(resto, 1)
    print(f"\ntesti con la firma: {c.trovati} · {'da correggere (prova)' if prova else 'corretti'}: {c.fatti}"
          + (" · giro interrotto al limite, il prossimo riprende" if interrotto
             else f" · rimasti per il prossimo giro: {resto}" if resto > 0 else ""))
    return resto


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--evento", action="store_true", help="corregge il testo dell'evento GitHub in corso")
    g.add_argument("--tutti", action="store_true", help="passa tutti i testi dal giorno indicato")
    ap.add_argument("--dal", default="", help="data di inizio AAAA-MM-GG (con --tutti)")
    ap.add_argument("--giorni", type=int, default=3, help="in alternativa a --dal: ultimi N giorni")
    ap.add_argument("--max", type=int, default=400, help="massimo di correzioni per giro (limiti di GitHub)")
    ap.add_argument("--giri", type=int, default=1, help="giri al massimo, finché resta qualcosa")
    ap.add_argument("--pausa", type=int, default=3700, help="secondi di attesa fra un giro e l'altro")
    ap.add_argument("--prova", action="store_true", help="elenca senza modificare")
    a = ap.parse_args()
    if not TOKEN and not a.prova:
        print("GITHUB_TOKEN mancante", file=sys.stderr)
        return 2
    if a.evento:
        return modo_evento()
    dal = a.dal or time.strftime("%Y-%m-%d", time.gmtime(time.time() - a.giorni * 86400))
    for giro in range(1, a.giri + 1):
        print(f"=== giro {giro} di {a.giri}, testi dal {dal} ===", flush=True)
        resto = modo_tutti(dal, a.max, a.prova)
        if resto <= 0 or a.prova or giro == a.giri:
            break
        print(f"attendo {a.pausa} s per i limiti di GitHub sulle scritture", flush=True)
        time.sleep(a.pausa)
    return 0


if __name__ == "__main__":
    sys.exit(main())
